### ISSUE TITLE
Update Storage configuration example

### ISSUE THREAD

**Issue by trevorquinn** [rhtconsulting/openshift-playbooks#12]
Example should match recommendations, using LVs over partitions. In to-be-commited oct-meetup branch.

**Comment by etsauer** [comment]
@trevorquinn addressed in https://github.com/rhtconsulting/openshift-playbooks/pull/17

**Comment by JaredBurck** [comment]
@etsauer Can we close this as well since #17 has been merged?

**Comment by etsauer** [comment]
@JaredBurck yes, i think so. I'll close
