### ISSUE TITLE
No need to change folder ownership

### ISSUE THREAD

**Issue by soggiest** [rhtconsulting/openshift-playbooks#16]
Since td-agent needs to run as root, rather than as td-agent, there is no need to change the ownership of the /etc/td-agent or /var/log/td-agent/tmp directories.

I recommend removing these steps.

**Comment by etsauer** [comment]
@soggiest Can we close this now that your PR has merged?

**Comment by soggiest** [comment]
Yup, I'll go ahead and close it.
