### ISSUE TITLE
Jekyll build should be dockerized

### ISSUE THREAD

**Issue by jeffcpullen** [rhtconsulting/openshift-playbooks#44]
I had one working, but then I saw https://github.com/rhtconsulting/rhc-ose/tree/openshift-enterprise-3/docker/jekyll-asciidoc-docker from @sabre1041 and it is way better. Can we copy his docker folder into this project and update the getting started directions to just use that instead?

**Comment by etsauer** [comment]
This makes sense to me. I think having a hard requirement on the other repo to be able to build this site is unreasonable.

@sabre1041 thoughts?

**Comment by sabre1041** [comment]
@etsauer i would recommend the `jekyll-asciidoc-docker` project in `rhc-ose` be the source of truth. copying it into this project could cause it to drift as changes are made to the upstream version. 

The primary reason is is located in `rhc-ose` is to support building multiple jekyll based repositories

**Comment by JaredBurck** [comment]
@etsauer @sabre1041 Seems like this issue can be closed since the Jekyll build is now dockerized using the jekyll-ascii-docker directory.  Can this issue be closed now?

**Comment by JaredBurck** [comment]
reopen if needed
