### ISSUE TITLE
Broken links and missing GitHub images in Jekyll website

### ISSUE THREAD

**Issue by JaredBurck** [rhtconsulting/openshift-playbooks#53]
Created the website using our docker container.  The image for the Contribute to GitHub! link is not displaying (404).  The path for the image is not found "img src=/assets/GitHub-Mark-32px.png".  Also found the STI JWS and Known Bugs links in the OSE 3 TroubleShooting page are broken (pages not found). The Playbooks index page is also broken; displaying HTML markup instead of rendering the page with list item links.

**Comment by sabre1041** [comment]
@JaredBurck @etsauer can this issue be closed?

**Comment by etsauer** [comment]
Should be closed, but i'll leave it to @JaredBurck since he opened it.
