### ISSUE TITLE
JBoss Image Repository name in the S2I overview has changed

### ISSUE THREAD

**Issue by etsauer** [rhtconsulting/openshift-playbooks#91]
Under the heading "JBoss EAP Integration" is the following command:

`docker run -it --rm --entrypoint=/bin/bash registry.access.redhat.com/jboss-eap-6/eap-openshift`

That image name no longer exists and needs updating.

@sabre1041

**Comment by sabre1041** [comment]
@etsauer while tackling this issue, there are references to images in the [disconnected environments](https://github.com/rhtconsulting/openshift-playbooks/blob/master/playbooks/installation/disconnected_environments.adoc) and [disconnected satellite](https://github.com/rhtconsulting/openshift-playbooks/blob/master/playbooks/installation/disconnected_satellite6.adoc). Many of them have also changed and new ones have been added. Do we want to track that in a separate issue?

**Comment by etsauer** [comment]
@sabre1041 i think we can use this issue to track image updates
